//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutuphane_otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal
    {
        public int personel_id { get; set; }
        public string personal_ad { get; set; }
        public string personal_soyad { get; set; }
        public string personal_tc { get; set; }
        public string personal_tel { get; set; }
        public string personal_mail { get; set; }
        public string personal_kulAd { get; set; }
        public string personal_sifre { get; set; }
    }
}
